// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tweetz.MicroServices.LiveService.Data;

#nullable disable

namespace Tweetz.MicroServices.LiveService.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250827141901_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tweetz.MicroServices.LiveService.Models.Live", b =>
                {
                    b.Property<string>("ApiVideoLiveStreamId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LIVE_ApiVideoLiveStreamId");

                    b.Property<string>("ApiVideoStreamKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_ApiVideoStreamKey");

                    b.Property<bool?>("Broadcasting")
                        .IsRequired()
                        .HasColumnType("bit")
                        .HasColumnName("LIVE_Broadcasting");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LIVE_CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_Description");

                    b.Property<DateTime?>("EndTime")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("LIVE_EndTime");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit")
                        .HasColumnName("LIVE_IsPublic");

                    b.Property<string>("PlayerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_PlayerUrl");

                    b.Property<DateTime?>("StartTime")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("LIVE_StartTime");

                    b.Property<int>("StreamerId")
                        .HasColumnType("int")
                        .HasColumnName("LIVE_StreamerId");

                    b.Property<string>("StreamerUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_StreamerUsername");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_ThumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LIVE_Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LIVE_UpdatedAt");

                    b.Property<int?>("ViewCount")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("LIVE_ViewCount");

                    b.Property<int?>("Views")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("LIVE_Views");

                    b.HasKey("ApiVideoLiveStreamId");

                    b.ToTable("LIVE");
                });
#pragma warning restore 612, 618
        }
    }
}
