services:
    dbTweetz:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: dbTweetz
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=YourStrongPassword123!
        ports:
            - "1433:1433"
        volumes:
            - dbTweetz:/var/opt/mssql
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrongPassword123!" -Q "SELECT 1" || exit 1
            interval: 10s
            timeout: 5s
            retries: 5

    init-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        depends_on:
            dbTweetz:
                condition: service_healthy
        command: /opt/mssql-tools/bin/sqlcmd -S dbTweetz -U sa -P "YourStrongPassword123!" -Q "CREATE DATABASE LiveStreamingDB"

volumes:
    dbTweetz:
